application:
    workingDir: "./BukkitDevelopREPL"

    # REPL commands in this setting will have been executed automatically on the startup of this program.
    #
    # autoexec:
    #     [ "installPlugins"
    #     , "startServer"
    #     , "newClient DEV"
    #     , "newClient DEV2 --version 1.12.2"
    #     ]
    autoexec: []

server:
    # Acceptable values: "Paper" and "Spigot"
    brand: "Paper"

    version: "1.20.1"

    jvmOptions:
        [ "-Xms2G"
        , "-Xmx2G"
        ]

    # The dependencies of your plugin should be put in here.
    # However, your plugin itself should be specified as a command line argument.
    # Because these plugins will not have been reinstalled unless their file name have changed.
    # Both urls and paths are acceptable.
    #
    # staticPlugins:
    #     [ "./dependencies/coreprotect.jar"
    #     , "./dependencies/placeholderapi.jar"
    #     , "https://modrinth.com/luckperms.jar"
    #     ]
    staticPlugins: []

    port: 25565

    # Using online mode will make dev clients unusable.
    onlineMode: false

    motd: "Plugin DEV Server"

    maxPlayers: 5

    enableCommandBlocks: true

    # Acceptable values: "survival", "creative", "adventure", "spectator" and 0-3
    defaultGameMode: "creative"

client:
    defaultVersion: "1.20.1"

    jvmOptions:
        [ "-Xms2G"
        , "-Xmx2G"
        , "-XX:+UnlockExperimentalVMOptions"
        , "-XX:+UseG1GC"
        , "-XX:G1NewSizePercent=20"
        , "-XX:G1ReservePercent=20"
        , "-XX:MaxGCPauseMillis=50"
        , "-XX:G1HeapRegionSize=32M"
        ]
